### ISSUE TITLE
Add method to check data integrity of archived files

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnrarKit#26]
it is nice to have a separate method for checkIntegrity via this RAR_TEST option.
also for UnzipKit via CRC check

**Comment by abbeycode** [comment]
Thanks for the suggestion. I'll take a look when I have some time.

**Comment by amosavian** [comment]
Any news :D

**Comment by abbeycode** [comment]
Nope, not yet – been busy with other tasks. I'm always open to pull requests, though :D

**Comment by amosavian** [comment]
I forgot it, found this after new GitHub update

**Comment by abbeycode** [comment]
Hey man, I finally got around to this. Check out PR #61 and let me know what you think! It turns out that the `RAR_TEST` command doesn't do what it sounds like. It just reads the file's data without extracting it. So I implemented it the way it'll most likely work in UnzipKit too, which is to extract and checksum the extracted data.

**Comment by abbeycode** [comment]
Merged! It'll be included in the next beta (2.9 beta 4)
