### ISSUE TITLE
Example doesn't run on device (only simulator)

### ISSUE THREAD

**Issue by gerchicov-bp** [abbeycode/UnrarKit#31]
Works in simulator, doesn't work on real device. The strangest thing is it is "compiled successfully" but the app is not installed on the device. Log:

dyld: Library not loaded: @rpath/UnrarKit.framework/UnrarKit
  Referenced from: /var/mobile/Containers/Bundle/Application/0FEBCED9-848A-4262-9399-7AA060C61F3E/UnrarExample.app/UnrarExample
  Reason: image not found

**Comment by gerchicov-bp** [comment]
Tried to create my own project and add this library via podfile/carthage - nothing works too. Carthage throws a lot of errors and even doesn't create workspace file

**Comment by abbeycode** [comment]
That's interesting - I'll have to try running the example project on-device later.

Regarding installation, though, I need more more information to help you out. Can you please provide the contents of your podfile and cartfile, the commands you're running to install dependencies, and the errors you're receiving?

Also, Carthage does not create a workspace file. It builds `.framework` files, which it's then up to you to link into your app.

**Comment by abbeycode** [comment]
I was able to confirm that no, the example indeed does not run on device. I spent some time with it and couldn't figure out what was going on. What's the reason you'd like to run it on-device in the first place?

**Comment by gerchicov-bp** [comment]
1)I currently use Unrar4iOS and it crashes because of memory troubles on real devices
2)yesterday I found out that both your library and Unrar4iOS use the same unrar library so your library may have the same crash. If you find it then don't try to replace unrar with  - I have tried with Unrar4iOS and this solution doesn't work

**Comment by gerchicov-bp** [comment]
I've replaced the option ```Mach-O Type```:
Dynamic Library -> Static Library
and now it seems workable. But I still need the way how to import it as sources (or as a link to project file with inner sources) but without of using carthage/pods

**Comment by abbeycode** [comment]
1. UnrarKit is a massively upgraded fork of Unrar4iOS
2. Yes, they both use the UnRAR library, but (a) UnrarKit is using a fully up to date version, whereas Unrar4iOS has been neglected, and (b) that's the **official** library from WinRAR, the company that created and owns the RAR spec
3. I actually added `-extractBufferedDataFromFile:error:action:` to UnrarKit so you can stream a file in pieces, rather than having the whole thing uncompressed in memory (Issue #4)
4. There shouldn't be any problem using UnrarKit as a static library (before iOS 8 that was the only option), but as long as you're targeting iOS 8 or above, it shouldn't be required. The example app was never meant to be run on device – it's merely intended as a demonstration of how to call into the library. If you're evaluating it, I would recommend doing so in your own project you plan to use it with, or in a new iOS project. In that case, it should run on-device, especially if you install using CocoaPods
5. Using CocoaPods (or Carthage) is the easiest way to make use of UnrarKit. I'm curious, what is your reason for not using either of those methods?

**Comment by abbeycode** [comment]
@gerchicov-bp Please feel free to reopen this issue I didn't address all of your concerns.
