### ISSUE TITLE
Feature request. Custom callback methods

### ISSUE THREAD

**Issue by gerchicov-bp** [abbeycode/UnrarKit#33]
```int CALLBACK CallbackProc(UINT msg, long UserData, long P1, long P2)```
```int CALLBACK BufferedReadCallbackProc(UINT msg, long UserData, long P1, long P2)```
These functions can be accessed from the code inside ```URKArchive.mm```.
What about to add a public way to access them? For example I want to customize ```UCM_CHANGEVOLUME``` event

**Comment by abbeycode** [comment]
In order to help design the API for this request, can you please provide some example use cases for this feature?

**Comment by gerchicov-bp** [comment]
https://github.com/fishman/rar_expander/blob/master/RarExpander.mm
It handles ```UCM_CHANGEVOLUME```. I can't find an info what does this code do but my project uses this event too. But anyways I could copy it "as is" because UnrarKit doesn't handle this event at all

**Comment by abbeycode** [comment]
Thanks, that link's helpful, but I'd still like to know how you plan to use the feature. Why is that event useful to you?

**Comment by gerchicov-bp** [comment]
Sorry but I can't post my code. The only thing I can say is it handles something like error and in some cases returns -1 (failure) but the default implementation (including UnrarKit) always returns 0 even doesn't allow to handle this event without editing of the library's sources

**Comment by abbeycode** [comment]
I'm not asking you to post code, I only mean _why_ do you need this feature? _Why_ is the `UCM_CHANGEVOLUME` event important to you? I'm looking for an explanation, not code.

As an example, for your other feature request, the answer could be "Because I'd like to show users in my app how much space a file will take up after he extracts it". I didn't ask for a use case for that feature, because I could picture use cases on my own. I don't currently see what you would use that callback for, so I'm asking you to help me understand.

**Comment by abbeycode** [comment]
@gerchicov-bp I've addressed your other feature request. If you're able to help me understand this request better, I can include this along with it on the next release.

**Comment by gerchicov-bp** [comment]
anyways I've already created a block which is called inside this static callback method but this block is defined as public and I can always override/redefine it.

**Comment by abbeycode** [comment]
Ok, feel free to submit a pull request to share back your contribution. I'm going to close this now - let me know if there's anything else I can do to help.
