### ISSUE TITLE
NSLog fallback prints all messages even on release

### ISSUE THREAD

**Issue by aonez** [abbeycode/UnrarKit#54]
At least for release, all non `URKLogError` or `URKLogFault` messages should be optional. Even those, since the functions printing this messages also return the `NSError`object.

Maybe I'm missing something.

**Comment by abbeycode** [comment]
Take a look at the Logging section of the new README (v2.9 or multivolume branches). Since I'm using the new unified logging framework, you have control over all logging. You could turn off all logging from `com.abbey-code.UnrarKit` if you'd like to. But why do you want to? The errors and warnings should be pretty uncommon, right? The idea is that when an error or fault occurs, that message and the info and debug logs that came before it will get saved so a developer can see what led to the error or fault. They can also provide additional details beyond what the `NSError` does.

**Comment by aonez** [comment]
I'm currently working on a Mac Mini '09 with Mac OS X 10.11.6, since 10.12+ is not supported on this oldie. Also Xcode is fixed to 8.2.1, here.

I'm getting on a release product all the logs that `URKLog` generates, not just `URKLogError`or `URKLogFault`.

**Comment by aonez** [comment]
Just tested on a macOS 10.13, Xcode 8.3.3. No logs in the release product. So seems only an issue with the fallback to `NSLog`.

**Comment by abbeycode** [comment]
That makes sense. Let's classify this as "won't fix", since `NSLog` support is going away.

**Comment by aonez** [comment]
So, a compiled version under Xcode 8.2.1, with 10.9 deployment target, prints all log messages on a macOS 10.13. I'll need to tweak this, since I not done with Xcode 8.2.1 and support for 10.8+...

**Comment by abbeycode** [comment]
That's correct, it goes by deployment target.
