### ISSUE TITLE
Integrating UnrarKit into SARUnArchiveANY

### ISSUE THREAD

**Issue by saru2020** [abbeycode/UnrarKit#72]
Hi,

First of all, Thanks for doing a Great job of supporting Rar unarchiving. 

I need your help in integrating UnrarKit into '[SARUnArchiveANY](https://github.com/saru2020/SARUnArchiveANY)'. 

**1.) Trying Cocoapods:**
I see that Cocoapods integration is not working and its throwing me these  linker errors.
<img width="269" alt="unrarkit_linkererrors" src="https://user-images.githubusercontent.com/1034916/36102795-6d34c386-1033-11e8-83f2-86ac01fbb72d.png">

**2.) Trying by Embedding Libs:**
When I go with the approach of embedding the UnrarKit framework file directly into SARUnArchiveAny lib, I don't see any good way to actually play around with the Universal frameworks (Slicing the framework based upon the architecture the project tries to build, since Universal frameworks are not officially supported or cannot be pushed along with the App store build). Any help here would be appreciated.

**3.) Manual Integration:**
I tried manually integrating UnrarKit by pulling all the unrar std lib source files & UnrarKit source files, but there multiple errors with the unrar std lib itself, with C++ files to be precise and frankly I tried solving them by adding the same compiler flags that you'd mentioned in your project, but had no luck in getting it to work. Any help here would also be helpful.

**4.) Carthage:**
I haven't yet tried it, but I just don't want users/devs to limit to this option, as most of the guys(including me) prefer to work with Cocoapods, though it has its own cons.

Any kind of guidance in integration would be helpful. Thanks!

**Comment by abbeycode** [comment]
@saru2020 Sorry you're having trouble. Can you give me more details on your project? To start with, which platform are you targeting, what OS version, and what does your podfile look like?

**Comment by saru2020** [comment]
Hi,
Thanks for replying back.
Don't be sorry about anything. You're doing a wonderful work :) 

[Here](https://www.dropbox.com/s/k4pauw7xlwaknaz/UnrarKit_Example.zip?dl=0) is the link to the project that I tried via Cocoapods Integration. Can you please take a look at it?

**Comment by abbeycode** [comment]
I think it's a simple problem with your podfile. You left the line commented out that defines the platform and version. It looks like you're targeting iOS 11, so use this at the top:

    platform :ios, '11.0'

Once I did that and ran `pod update`, I started getting more normal errors (code signing and things like that).

Also, a few minor suggestions based on the sample code you have there:

``` Objc
    NSData *data = [archive extractDataFromFile:filenames[0] progress:nil error:&error];
    
    if (error) {
        if (error.code == ERAR_MISSING_PASSWORD) {
            NSLog(@"Password protected archive!");
        }
    }
```

Generally with Objective-C you should check whether the return value is nil (or false), and then look for errors. I would also recommend comparing to the values in `URKErrorCode` rather than comparing directly to the Unrar constants (e.g. `URKErrorCodeMissingPassword`). Also, in UnrarKit v2.9 (currently in beta), I provide a `localizedDescription` that gives a readable version of the error.

I'm going to close the issue, but please feel free to reopen if this doesn't fix your problem, or to open another issue if you encounter other problems.

**Comment by saru2020** [comment]
Hey, Thanks for taking a look.
My bad, I did 2 mistakes, commented out the platform version as well as the 'use_frameworks' flag.
Uncommenting these 2 lines worked:
`platform :ios, '11.0'`
`use_frameworks!`
